export let banner_themes = [
    {
        bg_color: "linear-gradient(127.6deg, #D4DB58 43.83%, #71752F 71.75%)", //фон баннера
        image: "image/burger.png", //изображение баннера
        filter: "blur(30px)", //фильтр для тени изображения
        h1: "LETS COOK <br> NOW!", //заголовок баннера
        p: "На нашому сайті <br> зібрано багато рецептів <br>навіть для тих хто не <br> вміє готувати</p>", //опис баннера
        h3: "Чому б тобі не спробувати?" //подзаголовок баннера
    },
    {
        bg_color: "linear-gradient(127deg,rgba(255, 221, 140, 1) 0%, rgba(64, 47, 10, 1) 100%)",
        image: "image/coffee2.png",
        filter: " blur(35px)",
        h1: "ENJOY <br> YOUR COFFEE",
        p: "На нашому сайті <br> зібрано найсмачніші <br> кавові рецепти <br> для енергійного дня",
        h3: "Тримай чашку і вперед!"
    },
    {
        bg_color: "linear-gradient(127deg,rgba(193, 255, 179, 1) 0%, rgba(0, 36, 0, 1) 100%)",
        image: "image/cookie.png",
        filter: " blur(45px)",
        h1: "SWEET <br> TREATS",
        p: "На нашому сайті <br> зібрано найсолодші <br> рецепти печива <br> навіть для початківців",
        h3: "Спробуй прямо зараз!",
    },
    {
    bg_color: "linear-gradient(135deg, #FF9A8B 0%, #FF6A88 55%, #FF99AC 100%)",
    image: "image/pizza_margarita.png",
    filter: "blur(55px)",
    h1: "TIME FOR <br> PIZZA!",
    p: "Домашня піца — <br> це просто, швидко <br> та неймовірно смачно",
    h3: "Готуємо разом?"
},
{
    bg_color: "linear-gradient(135deg, #A1C4FD 0%, #C2E9FB 100%)",
    image: "image/smoothie.png",
    filter: "blur(60px)",
    h1: "FRESH & <br> HEALTHY",
    p: "Корисні смузі <br> для енергії, <br> настрою та сили",
    h3: "Почни день правильно"
},
{
    bg_color: "linear-gradient(135deg, #FDC830 0%, #F37335 100%)",
    image: "image/spageti.png",
    filter: "blur(40px)",
    h1: "PASTA <br> MOOD",
    p: "Вершкові соуси, <br> гриби та паста <br> як в ресторані",
    h3: "Смак Італії вдома"
},
{
    bg_color: "linear-gradient(135deg, #84FAB0 0%, #8FD3F4 100%)",
    image: "image/meatball_soup.png",
    filter: "blur(45px)",
    h1: "WARM & <br> COZY",
    p: "Супи та крем-супи <br> для затишку <br> у будь-яку пору",
    h3: "Тепло в кожній ложці"
},


]

export let recepts_data = [
   {title: "Бургер з куркою", //название
    id: 1, //айди
    ingredients: "Для приготування одного бургера тобі знадобиться булка для бургера, трохи вершкового масла або олії для підсмаження, 150–180 грамів яловичого фаршу, сіль, чорний перець, кілька скибочок помідора, кільця цибулі, лист салату, кілька кружечків маринованого огірка, одна-дві скибочки сиру чеддер, а також простий соус, який складається з майонезу, кетчупу та гірчиці.", //ингредиенты
    steps: "Спочатку приготуй соус: змішай майонез із кетчупом і гірчицею до однорідної маси та відстав убік. Далі займися м’ясом. Візьми фарш і сформуй котлету трохи більшого розміру, ніж булка, оскільки під час смаження вона зменшиться. Розігрій сковороду, посоли й поперчи котлету зверху й обсмаж її приблизно 3–4 хвилини з одного боку. Потім переверни, поклади зверху сир і смаж ще близько 2–3 хвилин, поки котлета повністю не приготується, а сир не розплавиться. Поки котлета смажиться, підготуй булку. Розріж її навпіл, змасти внутрішню сторону вершковим маслом і підсмаж на сковороді до легкої золотистої скоринки. Коли всі компоненти готові, можна збирати бургер. На нижню частину булки нанеси соус, зверху виклади лист салату, потім поклади гарячу котлету з розплавленим сиром, додай помідор, цибулю та мариноване огурок. Накрий бургер верхньою частиною булки і подавай одразу, поки вон теплий та соковитий.", //приготовление
    diet: "Ситні", //диета все возможные варианты: Ситнї Легка
    time: "Швидке", //время все возможные варианты: Швидке Довге
    method: "На сковороді", //метод все возможные варианты: На сковороді, У духовці, Без жарки, Без випічки
    dificult: "Легка", //сложность все возможные варианты: Легка, Складна
    isNew: "Нове", //новизна все возможные варианты: Нове, Старе
    img: "image/burger.png", //изображение
    bg: 'linear-gradient(135deg, #8E3200 0%, #FFB26B 100%)', //фон карточки
    like: false //нравится или нет по умолчанию false
   },
  {
    title: "Капучіно",
    id: 2,
    ingredients: "Кава, молоко, цукор. Потрібно підігріти молоко і збити його в піну, заварити еспресо та змішати з молочною піною, додати цукор за смаком.",
    steps: "Заварити еспресо. Підігріти молоко і збити до утворення пінки. Налити каву в чашку, додати молочну піну зверху. Посипати трохи какао за бажанням і подавати.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/coffee2.png",
    bg: 'linear-gradient(135deg, #6F4E37 0%, #C7A17A 100%)',
    like: false
  },
  {
    title: "Шоколадне печиво",
    id: 3,
    ingredients: "Борошно, цукор, масло, яйця, какао-порошок, шоколадні шматочки.",
    steps: "Змішати масло і цукор до кремоподібної консистенції. Додати яйця, борошно та какао. Вмішати шоколадні шматочки. Викладати тісто на деко та випікати при 180°C 10–12 хвилин.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/cookie.png",
    bg: 'linear-gradient(135deg, #FCEABB 0%, #F8B500 100%)',
    like: false
  },
  {
    title: "Салат Цезар",
    id: 4,
    ingredients: "Листя салату, куряче філе, сухарики, сир Пармезан, соус Цезар.",
    steps: "Обсмажити курку, нарізати салат і сир. Змішати всі інгредієнти з соусом і подавати.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/cesar.png",
    bg: 'linear-gradient(135deg, #56AB2F 0%, #A8E063 100%)',
    like: false
  },
  {
    title: "Піца Маргарита",
    id: 5,
    ingredients: "Тісто для піци, томатний соус, сир Моцарела, базилік.",
    steps: "Розкачати тісто, нанести томатний соус, додати сир і базилік. Випікати при 220°C 10–15 хвилин.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Нове",
    img: "image/pizza_margarita.png",
    bg: 'linear-gradient(135deg, #FAD961 0%, #F76B1C 100%)',
    like: false
  },
  {
    title: "Смузі з бананом та ягодами",
    id: 6,
    ingredients: "Банан, ягоди, йогурт або молоко, мед за смаком.",
    steps: "Змішати всі інгредієнти у блендері до однорідної консистенції. Налити в склянку і подавати одразу.",
    diet: "Ситні",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/smoothie.png",
    bg: 'linear-gradient(135deg, #FF9A9E 0%, #FAD0C4 100%)',
    like: false
  },
  {
    title: "Омлет з овочами",
    id: 7,
    ingredients: "Яйця, молоко, сіль, перець, помідор, болгарський перець, зелень.",
    steps: "Збити яйця з молоком, додати сіль і перець. Обсмажити овочі на сковороді 3–4 хвилини, залити яйцями і готувати на середньому вогні 5–7 хвилин до готовності.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/omlet.png",
    bg: 'linear-gradient(135deg, #FDEB71 0%, #F8D800 100%)',
    like: false
},
{
    title: "Суп-пюре з гарбуза",
    id: 8,
    ingredients: "Гарбуз, цибуля, морква, вершки, сіль, спеції.",
    steps: "Нарізати овочі, відварити до м'якості, подрібнити блендером до пюре, додати вершки і спеції, прогріти ще кілька хвилин.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Старе",
    img: "image/pumpkin_soup.png",
    bg: 'linear-gradient(135deg, #F2994A 0%, #EB5757 100%)',
    like: false
},
{
    title: "Тост з авокадо",
    id: 9,
    ingredients: "Хліб, авокадо, сіль, лимонний сік, помідор.",
    steps: "Підсмажити хліб, розім’яти авокадо з сіллю і лимоном, намазати на тост, зверху покласти скибочки помідора.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/avocado_toast.png",
    bg: 'linear-gradient(135deg, #9BE15D 0%, #00E3AE 100%)',
    like: false
},
{
    title: "Макарони з соусом Болоньєзе",
    id: 10,
    ingredients: "Макарони, фарш, цибуля, морква, томатна паста, спеції.",
    steps: "Обсмажити фарш з овочами, додати томатну пасту та спеції, тушкувати 15–20 хвилин. Відварити макарони та змішати з соусом.",
    diet: "Ситні",
    time: "Довге",
    method: "На сковороді",
    dificult: "Складна",
    isNew: "Старе",
    img: "image/spageti.png",
    bg: 'linear-gradient(135deg, #F2994A 0%, #F2C94C 100%)',
    like: false
},
{
    title: "Паста з вершковим соусом та грибами",
    id: 11,
    ingredients: "Для приготування пасти знадобиться 200 грамів макаронів, 200 грамів печериць, 150 мл вершків, один зубчик часнику, сіль, перець та трохи оливкової олії.",
    steps: "Відвари пасту до стану аль денте. Гриби наріж та обсмаж з часником на оливковій олії. Додай вершки, сіль і перець, прогрій соус. Змішай пасту з соусом та подавай гарячою.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/pasta_mushrooms.png",
    bg: "linear-gradient(135deg, #6F4E37 0%, #CDB4DB 100%)",
    like: false
},
{
    title: "Рис з овочами по-азійськи",
    id: 12,
    ingredients: "Для страви знадобиться 200 грамів рису, морква, солодкий перець, зелена цибуля, соєвий соус та рослинна олія.",
    steps: "Відвари рис. Овочі наріж і швидко обсмаж на сильному вогні. Додай рис та соєвий соус, перемішай і прогрій кілька хвилин.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/asian_rice.png",
    bg: "linear-gradient(135deg, #2B9348 0%, #80ED99 100%)",
    like: false
},
{
    title: "Куряче філе з медово-гірчичним соусом",
    id: 13,
    ingredients: "Для приготування знадобиться куряче філе, мед, гірчиця, сіль, перець та оливкова олія.",
    steps: "Філе обсмаж до золотистої скоринки. Змішай мед з гірчицею, додай до м’яса і прогрій кілька хвилин до карамелізації.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/chicken_honey.png",
    bg: "linear-gradient(135deg, #F48C06 0%, #FFD166 100%)",
    like: false
},
{
    title: "Овочеве рагу",
    id: 14,
    ingredients: "Для рагу знадобиться картопля, кабачок, морква, цибуля, томати та спеції.",
    steps: "Наріж овочі, виклади у сковороду або каструлю та туши на повільному вогні до м’якості.",
    diet: "Легка",
    time: "Довге",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/vegetable_stew.png",
    bg: "linear-gradient(135deg, #6A994E 0%, #A7C957 100%)",
    like: false
},
{
    title: "Млинці з медом",
    id: 15,
    ingredients: "Для млинців знадобиться молоко, яйця, борошно, сіль та мед для подачі.",
    steps: "Змішай інгредієнти для тіста. Смаж тонкі млинці на розігрітій сковороді до рум’яності.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/pancakes.png",
    bg: "linear-gradient(135deg, #FFB703 0%, #FFD6A5 100%)",
    like: false
},
{
    title: "Запечене куряче стегно",
    id: 16,
    ingredients: "Для страви знадобиться куряче стегно, спеції, сіль, перець та оливкова олія.",
    steps: "Замаринуй курку зі спеціями та запікай у духовці при 190°C близько 40 хвилин.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/baked_chicken.png",
    bg: "linear-gradient(135deg, #9A031E 0%, #E36414 100%)",
    like: false
},
{
    title: "Крем-суп з броколі",
    id: 17,
    ingredients: "Для супу знадобиться броколі, картопля, вершки, сіль та перець.",
    steps: "Відвари овочі до м’якості, збий блендером, додай вершки та спеції.",
    diet: "Легка",
    time: "Довге",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/broccoli_soup.png",
    bg: "linear-gradient(135deg, #2D6A4F 0%, #95D5B2 100%)",
    like: false
},
{
    title: "Вівсянка з фруктами",
    id: 18,
    ingredients: "Для приготування знадобиться вівсянка, молоко або вода та свіжі фрукти.",
    steps: "Відвари вівсянку, додай нарізані фрукти та перемішай.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/oatmeal.png",
    bg: "linear-gradient(135deg, #D4A373 0%, #FAEDCD 100%)",
    like: false
},
{
    title: "Домашній хот-дог",
    id: 19,
    ingredients: "Для хот-догу знадобиться булка, сосиска, гірчиця, кетчуп та цибуля.",
    steps: "Підігрій сосиску, булку розріж і злегка підігрій. Збери хот-дог із соусами.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/hotdog.png",
    bg: "linear-gradient(135deg, #6A040F 0%, #FAA307 100%)",
    like: false
},
{
    title: "Запіканка з картоплі та сиру",
    id: 20,
    ingredients: "Картопля, твердий сир, яйця, вершки, сіль, чорний перець.",
    steps: "Відвари картоплю та наріж кружальцями. Виклади шарами у форму, залий сумішшю яєць і вершків, посип сиром. Запікай до золотистої скоринки.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/potato_casserole.png",
    bg: "linear-gradient(135deg, #F7D046 0%, #C6862E 100%)",
    like: false
},
{
    title: "Гречка з грибами",
    id: 21,
    ingredients: "Гречка, печериці, цибуля, олія, сіль, перець.",
    steps: "Відвари гречку. Обсмаж гриби з цибулею, змішай з гречкою та прогрій кілька хвилин.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/buckwheat_mushrooms.png",
    bg: "linear-gradient(135deg, #C9B37E 0%, #7A6A42 100%)",
    like: false
},
{
    title: "Риба в клярі",
    id: 22,
    ingredients: "Філе білої риби, яйце, борошно, молоко, сіль, олія.",
    steps: "Приготуй кляр, занур рибу та обсмаж до золотистої скоринки.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/fish_batter.png",
    bg: "linear-gradient(135deg, #9AD0EC 0%, #1572A1 100%)",
    like: false
},
{
    title: "Салат з буряка та фети",
    id: 23,
    ingredients: "Варений буряк, сир фета, волоські горіхи, оливкова олія.",
    steps: "Наріж буряк, додай фету та горіхи, заправ оливковою олією.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/beet_feta_salad.png",
    bg: "linear-gradient(135deg, #D72638 0%, #7A0C1D 100%)",
    like: false
},
{
    title: "Курячі котлети на пару",
    id: 24,
    ingredients: "Курячий фарш, яйце, цибуля, сіль, перець.",
    steps: "Сформуй котлети та приготуй на пару до готовності.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/steamed_cutlets.png",
    bg: "linear-gradient(135deg, #EDE6DB 0%, #C1B7A1 100%)",
    like: false
},
{
    title: "Плов з овочами",
    id: 25,
    ingredients: "Рис, морква, цибуля, часник, спеції, олія.",
    steps: "Обсмаж овочі, додай рис і воду, туши до готовності.",
    diet: "Ситні",
    time: "Довге",
    method: "На сковороді",
    dificult: "Складна",
    isNew: "Старе",
    img: "image/veg_plov.png",
    bg: "linear-gradient(135deg, #F4A261 0%, #9A4C1E 100%)",
    like: false
},
{
    title: "Запечені кабачки з сиром",
    id: 26,
    ingredients: "Кабачки, твердий сир, часник, оливкова олія.",
    steps: "Наріж кабачки, посип сиром та запікай до рум’яності.",
    diet: "Легка",
    time: "Швидке",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/zucchini_cheese.png",
    bg: "linear-gradient(135deg, #9AE66E 0%, #3A7D44 100%)",
    like: false
},
{
    title: "Сирники зі сметаною",
    id: 27,
    ingredients: "Творог, яйце, борошно, цукор, олія.",
    steps: "Сформуй сирники та обсмаж до золотистої скоринки.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/syrnyky.png",
    bg: "linear-gradient(135deg, #FFF1C1 0%, #E6B566 100%)",
    like: false
},
{
    title: "Суп з фрикадельками",
    id: 28,
    ingredients: "Фарш, картопля, морква, цибуля, спеції.",
    steps: "Звари бульйон, додай овочі та фрикадельки, готуй до готовності.",
    diet: "Ситні",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/meatball_soup.png",
    bg: "linear-gradient(135deg, #FFD6A5 0%, #C97C5D 100%)",
    like: false
},
{
    title: "Фруктовий салат з йогуртом",
    id: 29,
    ingredients: "Яблуко, банан, апельсин, йогурт, мед.",
    steps: "Наріж фрукти, додай йогурт і трохи меду.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/fruit_salad.png",
    bg: "linear-gradient(135deg, #FFB703 0%, #FB8500 100%)",
    like: false
},
{
    title: "Картопля по-селянськи",
    id: 30,
    ingredients: "Картопля, паприка, часник, олія, сіль, спеції.",
    steps: "Наріж картоплю дольками, змішай зі спеціями та олією, запікай до рум’яної скоринки.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/potato_village.png",
    bg: "linear-gradient(135deg, #E9C46A 0%, #B08900 100%)",
    like: false
},
{
    title: "Рисова каша на молоці",
    id: 31,
    ingredients: "Рис, молоко, цукор, вершкове масло, сіль.",
    steps: "Вари рис у молоці на повільному вогні до м’якості, додай масло.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/rice_porridge.png",
    bg: "linear-gradient(135deg, #FFF3B0 0%, #E09F3E 100%)",
    like: false
},
{
    title: "Курячий суп з локшиною",
    id: 32,
    ingredients: "Куряче філе, локшина, морква, цибуля, спеції.",
    steps: "Звари бульйон, додай овочі та локшину, готуй до готовності.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/chicken_noodle_soup.png",
    bg: "linear-gradient(135deg, #FFE5B4 0%, #C97C5D 100%)",
    like: false
},
{
    title: "Запечений лосось з лимоном",
    id: 33,
    ingredients: "Філе лосося, лимон, оливкова олія, сіль, перець.",
    steps: "Полий рибу олією та лимонним соком, запікай до ніжності.",
    diet: "Ситні",
    time: "Швидке",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/salmon_lemon.png",
    bg: "linear-gradient(135deg, #FF9F1C 0%, #FF5400 100%)",
    like: false
},
{
    title: "Овочі гриль",
    id: 34,
    ingredients: "Кабачок, баклажан, перець, оливкова олія, спеції.",
    steps: "Наріж овочі, обсмаж на грилі або сковороді до м’якості.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/grilled_vegetables.png",
    bg: "linear-gradient(135deg, #90BE6D 0%, #2D6A4F 100%)",
    like: false
},
{
    title: "Яєчня з беконом",
    id: 35,
    ingredients: "Яйця, бекон, сіль, перець.",
    steps: "Обсмаж бекон, додай яйця та готуй до бажаної консистенції.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/eggs_bacon.png",
    bg: "linear-gradient(135deg, #F4A261 0%, #8D3B00 100%)",
    like: false
},
{
    title: "Салат з тунцем",
    id: 36,
    ingredients: "Тунець консервований, салат, яйце, оливкова олія.",
    steps: "Змішай всі інгредієнти та заправ олією.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/tuna_salad.png",
    bg: "linear-gradient(135deg, #A8DADC 0%, #457B9D 100%)",
    like: false
},
{
    title: "Домашня піта з овочами",
    id: 37,
    ingredients: "Піта, помідор, огірок, соус, салат.",
    steps: "Начини піту овочами та соусом, подавай одразу.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/pita_veggies.png",
    bg: "linear-gradient(135deg, #F1FAEE 0%, #A8DADC 100%)",
    like: false
},
{
    title: "Запечені яблука з медом",
    id: 38,
    ingredients: "Яблука, мед, кориця.",
    steps: "Запікай яблука з медом та корицею до м’якості.",
    diet: "Легка",
    time: "Швидке",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/baked_apples.png",
    bg: "linear-gradient(135deg, #FFCAD4 0%, #D62828 100%)",
    like: false
},
{
    title: "Картопляне пюре",
    id: 39,
    ingredients: "Картопля, молоко, вершкове масло, сіль.",
    steps: "Відвари картоплю та розімни з молоком і маслом.",
    diet: "Ситні",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/mashed_potatoes.png",
    bg: "linear-gradient(135deg, #FFF1C1 0%, #E6B566 100%)",
    like: false
},
{
    title: "Домашній лимонад",
    id: 40,
    ingredients: "Лимон, вода, цукор, м’ята.",
    steps: "Вичави лимонний сік, змішай з водою та цукром.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/lemonade.png",
    bg: "linear-gradient(135deg, #FFF200 0%, #FFD000 100%)",
    like: false
},
{
    title: "Лаваш з сиром та зеленню",
    id: 41,
    ingredients: "Лаваш, твердий сир, зелень, вершкове масло",
    steps: "Натри сир, додай зелень, загорни в лаваш і обсмаж до рум’яної скоринки.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/lavash-cheese.png",
    bg: "linear-gradient(135deg, #FFE259 0%, #FFA751 100%)",
    like: false
},
{
    title: "Куряча грудка з паприкою",
    id: 42,
    ingredients: "Куряча грудка, паприка, оливкова олія, сіль",
    steps: "Натри курку спеціями та обсмаж до готовності.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/chicken-paprika.png",
    bg: "linear-gradient(135deg, #F2994A 0%, #F2C94C 100%)",
    like: false
},
{
    title: "Салат з капусти та моркви",
    id: 43,
    ingredients: "Капуста, морква, олія, сіль",
    steps: "Нашаткуй овочі, заправ олією та перемішай.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/cabbage-salad.png",
    bg: "linear-gradient(135deg, #56AB2F 0%, #A8E063 100%)",
    like: false
},
{
    title: "Картопляні деруни",
    id: 44,
    ingredients: "Картопля, яйце, борошно, олія",
    steps: "Натри картоплю, додай інгредієнти та обсмаж деруни.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/deruny.png",
    bg: "linear-gradient(135deg, #D1913C 0%, #FFD194 100%)",
    like: false
},
{
    title: "Рис з яйцем та зеленню",
    id: 45,
    ingredients: "Рис, яйце, зелень, соєвий соус",
    steps: "Обсмаж яйце, додай рис і зелень, перемішай.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/rice-egg.png",
    bg: "linear-gradient(135deg, #FCEABB 0%, #F8B500 100%)",
    like: false
},
{
    title: "Запечена цвітна капуста",
    id: 46,
    ingredients: "Цвітна капуста, оливкова олія, спеції",
    steps: "Запічи капусту в духовці до золотистості.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/cauliflower.png",
    bg: "linear-gradient(135deg, #C6FFDD 0%, #FBD786 100%)",
    like: false
},
{
    title: "Тости з сиром і помідором",
    id: 47,
    ingredients: "Хліб, сир, помідор",
    steps: "Виклади сир і помідор на хліб та підсмаж.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/cheese-toast.png",
    bg: "linear-gradient(135deg, #FDEB71 0%, #F8D800 100%)",
    like: false
},
{
    title: "Курячі рулетики з сиром",
    id: 48,
    ingredients: "Куряче філе, сир, спеції",
    steps: "Загорни сир у філе та запічи.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Нове",
    img: "image/chicken-rolls.png",
    bg: "linear-gradient(135deg, #ED213A 0%, #93291E 100%)",
    like: false
},
{
    title: "Овочевий суп",
    id: 49,
    ingredients: "Картопля, морква, цибуля, вода",
    steps: "Звари овочі до м’якості.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/veg-soup.png",
    bg: "linear-gradient(135deg, #A8E063 0%, #56AB2F 100%)",
    like: false
},
{
    title: "Макарони з сиром",
    id: 50,
    ingredients: "Макарони, сир, вершкове масло",
    steps: "Відвари макарони та змішай з сиром.",
    diet: "Ситні",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/mac-cheese.png",
    bg: "linear-gradient(135deg, #F7971E 0%, #FFD200 100%)",
    like: false
},
{
    title: "Запечені помідори з сиром",
    id: 51,
    ingredients: "Помідори, сир, спеції",
    steps: "Запічи помідори з сиром 15 хвилин.",
    diet: "Легка",
    time: "Швидке",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/baked-tomatoes.png",
    bg: "linear-gradient(135deg, #FF512F 0%, #DD2476 100%)",
    like: false
},
{
    title: "Каша булгур з овочами",
    id: 52,
    ingredients: "Булгур, овочі, спеції",
    steps: "Залий булгур окропом та додай овочі.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/bulgur.png",
    bg: "linear-gradient(135deg, #11998E 0%, #38EF7D 100%)",
    like: false
},
{
    title: "Оладки на кефірі",
    id: 53,
    ingredients: "Кефір, борошно, яйце, цукор",
    steps: "Змішай тісто та обсмаж оладки.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/oladky.png",
    bg: "linear-gradient(135deg, #FAD961 0%, #F76B1C 100%)",
    like: false
},
{
    title: "Салат з огірка та сметани",
    id: 54,
    ingredients: "Огірок, сметана, сіль",
    steps: "Наріж огірок і заправ сметаною.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/cucumber-salad.png",
    bg: "linear-gradient(135deg, #83EAF1 0%, #63A4FF 100%)",
    like: false
},
{
    title: "Манна каша",
    id: 55,
    ingredients: "Манка, молоко, цукор",
    steps: "Звари манку на молоці до густоти.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/semolina.png",
    bg: "linear-gradient(135deg, #FFF1EB 0%, #ACE0F9 100%)",
    like: false
},
{
    title: "Кускус з овочами",
    id: 56,
    ingredients: "Кускус, болгарський перець, морква, оливкова олія",
    steps: "Залий кускус окропом, додай обсмажені овочі та перемішай.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/couscous.png",
    bg: "linear-gradient(135deg, #FCE38A 0%, #F38181 100%)",
    like: false
},
{
    title: "Запечені печериці з часником",
    id: 57,
    ingredients: "Печериці, часник, оливкова олія",
    steps: "Змішай гриби з часником та запічи в духовці.",
    diet: "Легка",
    time: "Швидке",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/mushrooms-garlic.png",
    bg: "linear-gradient(135deg, #B79891 0%, #94716B 100%)",
    like: false
},
{
    title: "Пюре з батату",
    id: 58,
    ingredients: "Батат, вершкове масло, сіль",
    steps: "Відвари батат і зроби пюре.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/sweet-potato.png",
    bg: "linear-gradient(135deg, #F2994A 0%, #EB5757 100%)",
    like: false
},
{
    title: "Грінки з часником",
    id: 59,
    ingredients: "Хліб, часник, олія",
    steps: "Наріж хліб, натри часником і підсмаж.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/croutons.png",
    bg: "linear-gradient(135deg, #FAD961 0%, #F76B1C 100%)",
    like: false
},
{
    title: "Салат з квасолею та кукурудзою",
    id: 60,
    ingredients: "Квасоля, кукурудза, цибуля, олія",
    steps: "Змішай всі інгредієнти та заправ олією.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/bean-corn-salad.png",
    bg: "linear-gradient(135deg, #84FAB0 0%, #8FD3F4 100%)",
    like: false
},
{
    title: "Курячі нагетси домашні",
    id: 61,
    ingredients: "Куряче філе, яйце, панірувальні сухарі",
    steps: "Запаніруй курку та обсмаж до золотистості.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/nuggets.png",
    bg: "linear-gradient(135deg, #F7971E 0%, #FFD200 100%)",
    like: false
},
{
    title: "Овочева запіканка",
    id: 62,
    ingredients: "Кабачок, морква, яйце, сир",
    steps: "Змішай овочі з яйцем і запічи.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Нове",
    img: "image/veg-casserole.png",
    bg: "linear-gradient(135deg, #43CEA2 0%, #185A9D 100%)",
    like: false
},
{
    title: "Суп з сочевиці",
    id: 63,
    ingredients: "Сочевиця, морква, цибуля",
    steps: "Відвари сочевицю з овочами до м’якості.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/lentil-soup.png",
    bg: "linear-gradient(135deg, #FDC830 0%, #F37335 100%)",
    like: false
},
{
    title: "Сендвіч з тунцем",
    id: 64,
    ingredients: "Хліб, тунець, майонез, салат",
    steps: "Змішай тунець з майонезом і збери сендвіч.",
    diet: "Ситні",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/tuna-sandwich.png",
    bg: "linear-gradient(135deg, #56CCF2 0%, #2F80ED 100%)",
    like: false
},
{
    title: "Рис з кокосовим молоком",
    id: 65,
    ingredients: "Рис, кокосове молоко, сіль",
    steps: "Звари рис на кокосовому молоці.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/coconut-rice.png",
    bg: "linear-gradient(135deg, #FFFBD5 0%, #B20A2C 100%)",
    like: false
},
{
    title: "Запечені баклажани",
    id: 66,
    ingredients: "Баклажан, оливкова олія, спеції",
    steps: "Наріж баклажан та запічи в духовці.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/eggplant.png",
    bg: "linear-gradient(135deg, #8360C3 0%, #2EBF91 100%)",
    like: false
},
{
    title: "Пшенична каша з маслом",
    id: 67,
    ingredients: "Пшоно, вода, вершкове масло",
    steps: "Звари кашу та додай масло.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/millet.png",
    bg: "linear-gradient(135deg, #FEE140 0%, #FA709A 100%)",
    like: false
},
{
    title: "Салат з морської капусти",
    id: 68,
    ingredients: "Морська капуста, олія, кунжут",
    steps: "Заправ капусту олією та посип кунжутом.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/seaweed.png",
    bg: "linear-gradient(135deg, #11998E 0%, #38EF7D 100%)",
    like: false
},
{
    title: "Домашній кекс",
    id: 69,
    ingredients: "Борошно, яйця, цукор, масло",
    steps: "Змішай інгредієнти та випікай до готовності.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Старе",
    img: "image/cake.png",
    bg: "linear-gradient(135deg, #FCCB90 0%, #D57EEB 100%)",
    like: false
},
{
    title: "Яблучне пюре",
    id: 70,
    ingredients: "Яблука, вода, цукор",
    steps: "Відвари яблука та перебий у пюре.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/apple-puree.png",
    bg: "linear-gradient(135deg, #A1FFCE 0%, #FAFFD1 100%)",
    like: false
},
{
    title: "Фалафель з нуту",
    id: 71,
    ingredients: "Нут, цибуля, часник, спеції",
    steps: "Подрібни нут, сформуй кульки та обсмаж.",
    diet: "Легка",
    time: "Довге",
    method: "На сковороді",
    dificult: "Складна",
    isNew: "Нове",
    img: "image/falafel.png",
    bg: "linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)",
    like: false
},
{
    title: "Шакшука",
    id: 72,
    ingredients: "Яйця, томати, болгарський перець",
    steps: "Туши овочі та додай яйця.",
    diet: "Ситні",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/shakshuka.png",
    bg: "linear-gradient(135deg, #CB356B 0%, #BD3F32 100%)",
    like: false
},
{
    title: "Рататуй",
    id: 73,
    ingredients: "Кабачок, баклажан, томати",
    steps: "Наріж овочі та запічи.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Складна",
    isNew: "Старе",
    img: "image/ratatouille.png",
    bg: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    like: false
},
{
    title: "Салат з кіноа",
    id: 74,
    ingredients: "Кіноа, огірок, помідор",
    steps: "Відвари кіноа та змішай з овочами.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/quinoa-salad.png",
    bg: "linear-gradient(135deg, #F7971E 0%, #FFD200 100%)",
    like: false
},
{
    title: "Картопля фрі в духовці",
    id: 75,
    ingredients: "Картопля, олія, спеції",
    steps: "Запічи картоплю до хрумкості.",
    diet: "Ситні",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/fries.png",
    bg: "linear-gradient(135deg, #f12711 0%, #f5af19 100%)",
    like: false
},
{
    title: "Гаспачо",
    id: 76,
    ingredients: "Томати, огірок, часник",
    steps: "Подрібни все в блендері.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/gazpacho.png",
    bg: "linear-gradient(135deg, #ee0979 0%, #ff6a00 100%)",
    like: false
},
{
    title: "Брускета з томатами",
    id: 77,
    ingredients: "Хліб, томати, базилік",
    steps: "Підсмаж хліб та додай начинку.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/bruschetta.png",
    bg: "linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)",
    like: false
},
{
    title: "Рис з куркою теріякі",
    id: 78,
    ingredients: "Рис, курка, соус теріякі",
    steps: "Обсмаж курку та подай з рисом.",
    diet: "Ситні",
    time: "Довге",
    method: "На сковороді",
    dificult: "Складна",
    isNew: "Нове",
    img: "image/teriyaki.png",
    bg: "linear-gradient(135deg, #41295a 0%, #2F0743 100%)",
    like: false
},
{
    title: "Салат з авокадо та томатами",
    id: 79,
    ingredients: "Авокадо, томати, оливкова олія",
    steps: "Наріж та змішай.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/avocado-salad.png",
    bg: "linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)",
    like: false
},
{
    title: "Чіа-пудинг",
    id: 80,
    ingredients: "Насіння чіа, молоко",
    steps: "Залий чіа молоком та залиш.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/chia.png",
    bg: "linear-gradient(135deg, #8360c3 0%, #2ebf91 100%)",
    like: false
},
{
    title: "Печена гарбузова каша",
    id: 81,
    ingredients: "Гарбуз, пшоно",
    steps: "Запічи гарбуз та змішай з кашею.",
    diet: "Легка",
    time: "Довге",
    method: "У духовці",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/pumpkin-porridge.png",
    bg: "linear-gradient(135deg, #f2994a 0%, #f2c94c 100%)",
    like: false
},
{
    title: "Локшина з овочами",
    id: 82,
    ingredients: "Локшина, морква, перець",
    steps: "Обсмаж овочі та змішай з локшиною.",
    diet: "Легка",
    time: "Швидке",
    method: "На сковороді",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/noodles.png",
    bg: "linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)",
    like: false
},
{
    title: "Крем з маскарпоне та ягодами",
    id: 83,
    ingredients: "Маскарпоне, ягоди",
    steps: "Збий сир та додай ягоди.",
    diet: "Легка",
    time: "Швидке",
    method: "Без випічки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/mascarpone.png",
    bg: "linear-gradient(135deg, #e96443 0%, #904e95 100%)",
    like: false
},
{
    title: "Риба на пару з лимоном",
    id: 84,
    ingredients: "Риба, лимон",
    steps: "Приготуй рибу на пару.",
    diet: "Легка",
    time: "Довге",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Старе",
    img: "image/steamed-fish.png",
    bg: "linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)",
    like: false
},
{
    title: "Домашній хумус",
    id: 85,
    ingredients: "Нут, тахіні, лимон",
    steps: "Збий усе в блендері.",
    diet: "Легка",
    time: "Швидке",
    method: "Без жарки",
    dificult: "Легка",
    isNew: "Нове",
    img: "image/hummus.png",
    bg: "linear-gradient(135deg, #fceabb 0%, #f8b500 100%)",
    like: false
}
]